secret:
  db:
    username: ""
    password: ""
    database: ""

rabbitmq:
  auth:
    username: ""
    password: ""
    erlangCookie: ""
  service:
    type: ClusterIP
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true

redis:
  architecture: standalone
  auth:
    enabled: true
    username: "default"
    password: ""
  commonConfiguration: |-
    databases 100

platform:
  name: "platform"
  enabled: true
  dockerconfig:
    registry: ""
    username: ""
    password: ""
  service:
    type: NodePort
    port: 9080
  imagePullSecrets:
    - name: credentials-registry
  image:
    repository: harbor.cuemby.io/cuemby-platform/cp-platform
    pullPolicy: Always
    tag: "v1.0.34-dev"
  environment:
    API_KEY: ""
    DB_USERNAME: ""
    DB_PASSWORD: ""
    DB_HOST: "cuemby-platform-core-db"
    DB_PORT: "5432"
    DB_DATABASE: "postgres"
    HARBOR_BASE_URL: ""
    HARBOR_USERNAME: ""
    HARBOR_PASSWORD: ""
    MINIO_ACCESS_KEY_ID: ""
    MINIO_SECRET_ACCESS_KEY: ""
    MINIO_ENDPOINT: ""
