secret:
  db:
    username: ""
    password: ""
    database: ""
  github:
    clientId: ""
    clientSecret: ""

rabbitmq:
  auth:
    username: ""
    password: ""
    erlangCookie: ""
  service:
    type: ClusterIP
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true

redis:
  architecture: standalone
  auth:
    enabled: true
    username: "default"
    password: ""
  commonConfiguration: |-
    databases 100

platform:
  name: "platform"
  enabled: true
  dockerconfig:
    registry: ""
    username: ""
    password: ""
  service:
    type: NodePort
    port: 9080
  imagePullSecrets:
    - name: credentials-registry
  image:
    repository: harbor.cuemby.io/cuemby-platform/cp-platform
    pullPolicy: Always
    tag: "v1.0.33-dev.23"
  environment:
    DB_USERNAME: ""
    DB_PASSWORD: ""
    DB_DATABASE: "postgres"
    DB_HOST: "cuemby-platform-core-db"
    DB_PORT: "5432"
    API_KEY: ""
    HARBOR_BASE_URL: ""
    HARBOR_USERNAME: ""
    HARBOR_PASSWORD: ""
    # REDIS_ADDR: "redis.sp.cuemby.io:6379"
    # REDIS_USERNAME: "default"
    # REDIS_PASSWORD: ""
    # REDIS_WEBHOOK_DB: "15"
