{{- if .Values.walrus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: walrus-system
  name: walrus-secrets
  labels:
    "app.kubernetes.io/part-of": "walrus"
    "app.kubernetes.io/component": "configuration"
stringData:
#   # Change to `true` if disabling TLS termination.
  local_environment_mode: ""
  enable_tls: ""
  db_driver: ""
  db_user: ""
  db_password: ""
  db_name: ""
  minio_root_user: ""
  minio_root_password: ""
  minio_bucket: ""
type: Opaque
{{- end }}
# Uncomment the following lines if consuming custom TLS.
#
