walrus:
  enabled: true
  environment:
    DATABASE_SERVICE_HOST: "cuemby-core-supabase-db.cuemby-system.svc.cluster.local"
  ingress:
    hosts:
      core: walrus.netsaj.uk
    className: cloudflare-tunnel

iam:
  enabled: true
  environment:
    DATABASE_SERVICE_HOST: "cuemby-core-supabase-db.cuemby-system.svc.cluster.local"
