secret:
  db:
    driver: "postgres"
    user: "supabase_admin"
    password: ""
    name: "walrus"
  minio:
    rootUser: ""
    rootPassword: ""

walrus:
  enabled: true
  environment:
    DATABASE_SERVICE_HOST: "cuemby-platform-core-db.cuemby-system.svc.cluster.local"
  ingress:
    hosts:
      core: ""
    className: nginx
    secretName: ""
    annotations: {}
  persistence:
    enabled: true
    storageClass: ""
    size: 500Mi
    accessModes:
      - ReadWriteOnce

iam:
  enabled: true
  environment:
    DATABASE_SERVICE_HOST: "cuemby-platform-core-db.cuemby-system.svc.cluster.local"
