apiVersion: v1
entries:
  configurator:
  - apiVersion: v2
    created: "2025-07-07T14:37:51.822688-05:00"
    dependencies:
    - name: keda
      repository: https://kedacore.github.io/charts
      version: 2.14.2
    - name: reloader
      repository: https://stakater.github.io/stakater-charts
      version: 1.0.104
    description: The cuemby platform configurator
    digest: 1dc72887201d59fb9f65a9bf7e6388f3c4625a482627ac0565489e091c5578ab
    name: configurator
    type: application
    urls:
    - configurator-1.0.0.tgz
    version: 1.0.0
  core:
  - apiVersion: v2
    created: "2025-07-07T14:37:51.825485-05:00"
    description: The open source Firebase alternative.
    digest: 24b55c94621ec33ba7e8ab1b7b1ab014149821fca6d89c317ffa36fd22b1d178
    icon: https://avatars.githubusercontent.com/u/54469796?s=280&v=4
    name: core
    type: application
    urls:
    - core-0.1.3.tgz
    version: 0.1.3
  cuemby-platform:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-07-07T14:37:51.840467-05:00"
    dependencies:
    - name: core
      repository: file://../cuemby-platform-core/core
      version: 0.1.3
    - name: walrus
      repository: file://../cuemby-platform-core/walrus
      version: 1.0.0
    - name: configurator
      repository: file://../cuemby-platform-core/configurator
      version: 1.0.0
    - name: platform
      repository: file://../cuemby-platform-core/platform
      version: 1.0.0
    - name: dashboard
      repository: file://../cuemby-platform-core/dashboard
      version: 1.0.0
    - alias: registry
      condition: registry.enabled
      name: harbor
      repository: https://helm.goharbor.io
      version: 1.14.0
    description: Meta chart que instala todos los componentes obligatorios de cuemby-platform-core
    digest: 79678477a267c12b7b894f7eca945cc8b2c4c66a474ccc1dff841714276d98b9
    name: cuemby-platform
    type: application
    urls:
    - cuemby-platform-1.0.0.tgz
    version: 1.0.0
  dashboard:
  - apiVersion: v2
    created: "2025-07-07T14:37:51.841016-05:00"
    description: The dashboard for the Cuemby Platform, providing a user interface
      for managing and monitoring the platform's components.
    digest: bb52fdd55d3adfe6d14bc8a2a67de900e938081e62c0054b0d0bf051b788610c
    name: dashboard
    type: application
    urls:
    - dashboard-1.0.0.tgz
    version: 1.0.0
  platform:
  - apiVersion: v2
    created: "2025-07-07T14:37:51.847029-05:00"
    dependencies:
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 12.0.0
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 17.11.3
    description: The platform is a service that provides the core functionalities
      of the Cuemby Platform.
    digest: 384d63dc7eb99b961ff5ba9c6ca24f5b26a8d03ee548172d6a93134104e7f96c
    name: platform
    type: application
    urls:
    - platform-1.0.0.tgz
    version: 1.0.0
  walrus:
  - apiVersion: v2
    created: "2025-07-07T14:37:51.847588-05:00"
    description: The walrus
    digest: 9f5e554fb54a45c9723fa55a6baba695b397a2caf744605bbda931041293dcf7
    name: walrus
    type: application
    urls:
    - walrus-1.0.0.tgz
    version: 1.0.0
generated: "2025-07-07T14:37:51.818426-05:00"
