apiVersion: v1
entries:
  configurator:
  - apiVersion: v2
    created: "2025-06-03T14:21:54.614779-05:00"
    description: The cuemby platform configurator
    digest: ae48e10ce012566ea3698a0fbed831c646fb6e75bf9a5b40ca4c52fd4531fd58
    name: configurator
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/configurator-1.0.0.tgz
    version: 1.0.0
  cuemby-platform:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-06-03T14:21:54.621079-05:00"
    dependencies:
    - name: supabase
      repository: file://../cuemby-platform-core/supabase
      version: 0.1.3
    - name: walrus
      repository: file://../cuemby-platform-core/walrus
      version: 1.0.0
    - name: configurator
      repository: file://../cuemby-platform-core/configurator
      version: 1.0.0
    - name: platform
      repository: file://../cuemby-platform-core/platform
      version: 1.0.0
    description: Meta chart que instala todos los componentes obligatorios de cuemby-platform-core
    digest: a26dcc735af6e6fb55e1f1615732c227197d5c2df84d0f72483bb6b5c44c1cbe
    name: cuemby-platform
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/cuemby-platform-1.0.0.tgz
    version: 1.0.0
  harbor:
  - apiVersion: v1
    appVersion: 2.9.0
    created: "2025-06-03T14:21:54.622717-05:00"
    description: An open source trusted cloud native registry that stores, signs,
      and scans content
    digest: e1a972f9198a2b7ea1b889c7a69f9eb7af844c417ad63ece274a244841feb17e
    home: https://goharbor.io
    icon: https://raw.githubusercontent.com/goharbor/website/main/static/img/logos/harbor-icon-color.png
    keywords:
    - docker
    - registry
    - harbor
    maintainers:
    - email: yinw@vmware.com
      name: Wenkai Yin
    - email: hweiwei@vmware.com
      name: Weiwei He
    - email: yshengwen@vmware.com
      name: Shengwen Yu
    name: harbor
    sources:
    - https://github.com/goharbor/harbor
    - https://github.com/goharbor/harbor-helm
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/harbor-1.13.0.tgz
    version: 1.13.0
  platform:
  - apiVersion: v2
    created: "2025-06-03T14:21:54.624891-05:00"
    dependencies:
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 12.0.0
    description: The platform is a service that provides the core functionalities
      of the Cuemby Platform.
    digest: 418e971f15e2528d4e7d7fc10a8f852477ff7a7f5b9e0f7e6ae28162b4ca0e38
    name: platform
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/platform-1.0.0.tgz
    version: 1.0.0
  supabase:
  - apiVersion: v2
    created: "2025-06-03T14:21:54.628037-05:00"
    description: The open source Firebase alternative.
    digest: 344e7eeaa2a74ace98e7b6bc3f78039130a5212a7af75be00bdae055712d2768
    icon: https://avatars.githubusercontent.com/u/54469796?s=280&v=4
    name: supabase
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/supabase-0.1.3.tgz
    version: 0.1.3
  walrus:
  - apiVersion: v2
    created: "2025-06-03T14:21:54.628248-05:00"
    description: The walrus
    digest: 6e1c651c91f3c98e7644e552f638d451ee0b02be991b47870b8036c4906eb6e9
    name: walrus
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/walrus-1.0.0.tgz
    version: 1.0.0
generated: "2025-06-03T14:21:54.614306-05:00"
