apiVersion: v1
entries:
  configurator:
  - apiVersion: v2
    created: "2025-06-03T09:24:56.986823-05:00"
    description: The cuemby platform configurator
    digest: 34ae479eeff8bd8a2a9f50e4343938c4d8a33041e4c20cbf3423967312eeb104
    name: configurator
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/charts/configurator-1.0.0.tgz
    version: 1.0.0
  cuemby-platform:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-06-03T09:24:56.992403-05:00"
    dependencies:
    - name: supabase
      repository: file://../cuemby-platform-core/supabase
      version: 0.1.3
    - name: walrus
      repository: file://../cuemby-platform-core/walrus
      version: 1.0.0
    - name: configurator
      repository: file://../cuemby-platform-core/configurator
      version: 1.0.0
    - name: platform
      repository: file://../cuemby-platform-core/platform
      version: 1.0.0
    description: Meta chart que instala todos los componentes obligatorios de cuemby-platform-core
    digest: 570574ff03f38d72e0db04baa9618445378e681a82accf32c41f3a434b45be9d
    name: cuemby-platform
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/charts/cuemby-platform-1.0.0.tgz
    version: 1.0.0
  harbor:
  - apiVersion: v1
    appVersion: 2.9.0
    created: "2025-06-03T09:24:56.993997-05:00"
    description: An open source trusted cloud native registry that stores, signs,
      and scans content
    digest: a352df0f1a4cbe10cd3537e4e5e41f56b91757da27cf919041a3983c8e82be95
    home: https://goharbor.io
    icon: https://raw.githubusercontent.com/goharbor/website/main/static/img/logos/harbor-icon-color.png
    keywords:
    - docker
    - registry
    - harbor
    maintainers:
    - email: yinw@vmware.com
      name: Wenkai Yin
    - email: hweiwei@vmware.com
      name: Weiwei He
    - email: yshengwen@vmware.com
      name: Shengwen Yu
    name: harbor
    sources:
    - https://github.com/goharbor/harbor
    - https://github.com/goharbor/harbor-helm
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/charts/harbor-1.13.0.tgz
    version: 1.13.0
  platform:
  - apiVersion: v2
    created: "2025-06-03T09:24:56.996519-05:00"
    dependencies:
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 12.0.0
    description: The platform is a service that provides the core functionalities
      of the Cuemby Platform.
    digest: e3e37bce825a77d7cd081cd30445d5831905297a884dbc56deddaae37831a153
    name: platform
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/charts/platform-1.0.0.tgz
    version: 1.0.0
  supabase:
  - apiVersion: v2
    created: "2025-06-03T09:24:56.999161-05:00"
    description: The open source Firebase alternative.
    digest: e13bb21ba4ef2dea247a4a2c9a52971af7bcdaea288b5f5428a0dbdc69e25c75
    icon: https://avatars.githubusercontent.com/u/54469796?s=280&v=4
    name: supabase
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/charts/supabase-0.1.3.tgz
    version: 0.1.3
  walrus:
  - apiVersion: v2
    created: "2025-06-03T09:24:56.999364-05:00"
    description: The walrus
    digest: fc6a88f62ba60139f5cec43007b61f204ced7ed387fdf09abb8d08406f23b0f8
    name: walrus
    type: application
    urls:
    - https://cuemby.github.io/cuemby-platform-helm-chart/charts/walrus-1.0.0.tgz
    version: 1.0.0
generated: "2025-06-03T09:24:56.986372-05:00"
