apiVersion: v1
entries:
  api-gateway:
  - apiVersion: v2
    created: "2025-07-24T22:42:40.780178-05:00"
    description: The API Gateway is a service that provides the API to functionalities
      of the CLI.
    digest: a9e52957baf8726e5fa3a47f64a2f4d4d558643749d49971afd519b04cb38df8
    name: api-gateway
    type: application
    urls:
    - api-gateway-1.0.0.tgz
    version: 1.0.0
  configurator:
  - apiVersion: v2
    created: "2025-07-24T22:42:40.784613-05:00"
    dependencies:
    - condition: keda.enabled
      name: keda
      repository: https://kedacore.github.io/charts
      version: 2.14.2
    - name: reloader
      repository: https://stakater.github.io/stakater-charts
      version: 1.0.104
    description: The cuemby platform configurator
    digest: 8a1215353ef6d3288b30fd5640b56121f9e6ac23f44a792cbf7218a65161f1c5
    name: configurator
    type: application
    urls:
    - configurator-1.0.0.tgz
    version: 1.0.0
  core:
  - apiVersion: v2
    created: "2025-07-24T22:42:40.786955-05:00"
    description: The open source Firebase alternative.
    digest: b817d8542466f401d654878ade59306089ef4a93a750163b6d6d7c91557b6ed7
    icon: https://avatars.githubusercontent.com/u/54469796?s=280&v=4
    name: core
    type: application
    urls:
    - core-0.1.3.tgz
    version: 0.1.3
  cuemby-platform:
  - apiVersion: v2
    appVersion: 2.0.2
    created: "2025-07-24T22:42:40.806954-05:00"
    dependencies:
    - name: core
      repository: file://../cuemby-platform-core/core
      version: 0.1.3
    - name: walrus
      repository: file://../cuemby-platform-core/walrus
      version: 1.0.0
    - name: configurator
      repository: file://../cuemby-platform-core/configurator
      version: 1.0.0
    - name: platform
      repository: file://../cuemby-platform-core/platform
      version: 1.0.0
    - name: dashboard
      repository: file://../cuemby-platform-core/dashboard
      version: 1.0.0
    - alias: monitoring
      condition: monitoring.enabled
      name: monitoring
      repository: file://../cuemby-platform-core/monitoring
      version: 2.0.0
    - alias: registry
      condition: registry.enabled
      name: harbor
      repository: https://helm.goharbor.io
      version: 1.14.0
    - condition: dkron.enabled
      name: dkron
      repository: https://raw.githubusercontent.com/distribworks/dkron-helm/master
      version: 2.0.3
    - alias: api-gateway
      condition: apiGateway.enabled
      name: api-gateway
      repository: file://../cuemby-platform-core/api-gateway
      version: 1.0.0
    description: Meta chart que instala todos los componentes obligatorios de cuemby-platform-core
    digest: 21715d91bec5a79ee7c00d0f622aecfb151636c5f168716036216088ea4dd6c5
    name: cuemby-platform
    type: application
    urls:
    - cuemby-platform-2.0.2.tgz
    version: 2.0.2
  dashboard:
  - apiVersion: v2
    created: "2025-07-24T22:42:40.807308-05:00"
    description: The dashboard for the Cuemby Platform, providing a user interface
      for managing and monitoring the platform's components.
    digest: fae64a4ff8d9739cdb16a55da1e9289f77ab74d777cb112eac8a196e79161a42
    name: dashboard
    type: application
    urls:
    - dashboard-1.0.0.tgz
    version: 1.0.0
  monitoring:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2025-07-24T22:42:40.811871-05:00"
    dependencies:
    - alias: victoria-metrics
      condition: victoria-metrics.enabled
      name: victoria-metrics-single
      repository: https://victoriametrics.github.io/helm-charts
      version: 0.9.15
    - name: fluent-bit
      repository: https://fluent.github.io/helm-charts
      version: 0.48.9
    - alias: victoria-logs
      condition: victoria-logs.enabled
      name: victoria-logs-single
      repository: https://victoriametrics.github.io/helm-charts
      version: 0.8.14
    description: Meta chart that installs all the monitoring components of cuemby-platform
    digest: ad0f28b9f1e201eed157066511968356e4b288f763a28dc1529088a59ffc5de2
    name: monitoring
    type: application
    urls:
    - monitoring-2.0.0.tgz
    version: 2.0.0
  platform:
  - apiVersion: v2
    created: "2025-07-24T22:42:40.819219-05:00"
    dependencies:
    - name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 16.0.11
    - name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 21.2.13
    description: The platform is a service that provides the core functionalities
      of the Cuemby Platform.
    digest: 2dc4e4ab62a723e7bf46e7e8cd4de8b09206763c2d04a5d5408e5b9082288440
    name: platform
    type: application
    urls:
    - platform-1.0.0.tgz
    version: 1.0.0
  walrus:
  - apiVersion: v2
    created: "2025-07-24T22:42:40.819606-05:00"
    description: The walrus
    digest: 358eccc56c13adefb9daeb7713d43fe533a7dfc7e3c311c9c7bbb16ff40fea6e
    name: walrus
    type: application
    urls:
    - walrus-1.0.0.tgz
    version: 1.0.0
generated: "2025-07-24T22:42:40.779767-05:00"
