apiVersion: v2
name: cuemby-platform
description: Meta chart que instala todos los componentes obligatorios de cuemby-platform-core
type: application
version: 2.0.2
appVersion: "2.0.2"

dependencies:
  - name: core
    version: 0.1.3
    repository: file://../cuemby-platform-core/core
  - name: walrus
    version: 1.0.0
    repository: file://../cuemby-platform-core/walrus
  - name: configurator
    version: 1.0.0
    repository: file://../cuemby-platform-core/configurator
  - name: platform
    version: 1.0.0
    repository: file://../cuemby-platform-core/platform
  - name: dashboard
    version: 1.0.0
    repository: file://../cuemby-platform-core/dashboard
  - name: monitoring
    alias: monitoring
    version: 2.0.0
    repository: file://../cuemby-platform-core/monitoring
    condition: monitoring.enabled
  - name: harbor
    alias: registry
    version: 1.14.0
    repository: https://helm.goharbor.io
    condition: registry.enabled
  - name: dkron
    version: 2.0.3
    repository: https://raw.githubusercontent.com/distribworks/dkron-helm/master
    condition: dkron.enabled
  - name: api-gateway
    alias: apiGateway
    version: 1.0.0
    repository: file://../cuemby-platform-core/api-gateway
    condition: apiGateway.enabled
