apiVersion: v2
name: cuemby-platform
description: Meta chart que instala todos los componentes obligatorios de cuemby-platform-core
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: supabase
    version: 0.1.3
    repository: file://../cuemby-platform-core/supabase
  - name: walrus
    version: 1.0.0
    repository: file://../cuemby-platform-core/walrus
  - name: configurator
    version: 1.0.0
    repository: file://../cuemby-platform-core/configurator
  - name: platform
    version: 1.0.0
    repository: file://../cuemby-platform-core/platform
  - name: harbor
    alias: registry
    version: 1.14.0
    repository: https://helm.goharbor.io
    condition: registry.enabled
