secret:
  db:
    username: ""
    password: ""
    database: ""
  github:
    clientId: ""
    clientSecret: ""

configurator:
  enabled: true
  dockerconfig:
    registry: ""
    username: ""
    password: ""
  imagePullSecrets:
    - name: credentials-registry
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: ""
  environment:
    # SupabaseDB
    PGPASSWORD: ""
    PGUSERNAME: ""
    DATABASE_NAME: ""
    PGPORT: ""
    PGHOST: ""
    GITHUB_CLIENT_SECRET: ""
    GITHUB_CLIENT_ID: ""
    WALRUS_NAMESPACE: ""
    WALRUS_SERVICE_NAME: ""
    WALRUS_BASE_URL: ""
    SUPABASE_FUNCTIONS_CP_CONFIG_MAP_NAME: ""
    SUPABASE_NAMESPACE: "default"
    SUPABASE_SERVICE_NAME: ""
    SUPABASE_FUNCTION_SERVICE_NAME: ""
    SUPABASE_DB_SERVICE_NAME: ""
