secret:
  db:
    username: ""
    password: ""
    database: ""
  github:
    clientId: ""
    clientSecret: ""

reloader:
  fullnameOverride: reloader

configurator:
  enabled: true
  dockerconfig:
    registry: ""
    username: ""
    password: ""
  imagePullSecrets:
    - name: credentials-registry
  image:
    repository: harbor.cuemby.io/cuemby-platform/cp-configurator
    pullPolicy: IfNotPresent
    tag: "v2.0.59-dev.7"
  environment:
    # SupabaseDB
    PGPASSWORD: ""
    PGUSERNAME: ""
    DATABASE_NAME: "postgres"
    PGPORT: "5432"
    PGHOST: "cuemby-platform-core-db"
    WALRUS_NAMESPACE: walrus-system
    SUPABASE_NAMESPACE: cuemby-system
    GITHUB_CLIENT_ID: ""
    GITHUB_CLIENT_SECRET: ""
    WALRUS_SERVICE_NAME: "walrus"
    SUPABASE_FUNCTIONS_CP_CONFIG_MAP_NAME: "cuemby-platform-core-functions-cp-config"
    SUPABASE_SERVICE_NAME: "cuemby-platform-core-functions"
    SUPABASE_FUNCTION_SERVICE_NAME: "cuemby-platform-core-functions"
    SUPABASE_DB_SERVICE_NAME: "cuemby-platform-core-db"
