{{- if .Values.platform.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cuemby-system
  name: platform
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/component: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-service
      app.kubernetes.io/part-of: "platform-service"
      app.kubernetes.io/component: "platform-service"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform-service
        app.kubernetes.io/part-of: "platform-service"
        app.kubernetes.io/component: "platform-service"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/component"
                      operator: In
                      values:
                        - "platform"
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - "platform"
      restartPolicy: Always
      {{- with .Values.platform.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: deletion-worker
          ports:
            - containerPort: 9081
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/deletionworker"]
          env:
            - name: API_KEY
              value: {{ .Values.platform.environment.API_KEY | quote }}
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-platform-rabbitmq:5672"
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
            - name: HARBOR_BASE_URL
              value: {{ .Values.platform.environment.HARBOR_BASE_URL | quote }}
            - name: HARBOR_USERNAME
              value: {{ .Values.platform.environment.HARBOR_USERNAME | quote }}
            - name: HARBOR_PASSWORD
              value: {{ .Values.platform.environment.HARBOR_PASSWORD | quote }}
            - name: WALRUS_USERNAME
              value: "admin"
            - name: WALRUS_BASE_URL
              value: "http://walru.walrus-system:80"
            - name: WALRUS_API_KEY
              value: ""
            - name: QUEUE_NAME_DELETION_WORKER
              value: "deletion_worker"
        - name: billingcron
          ports:
            - containerPort: 9085
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/billingcron"]
          env:
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
            - name: DKRON_URL_ADDR
              value: "http://cuemby-platform-dkron:8080"
            - name: CP_PLATFORM_V2_URL
              value: "https://platform-prod.cuemby.io/v1"
            - name: API_KEY
              value: {{ .Values.platform.environment.API_KEY | quote }}
            - name: METRICS_URL
              value: "http://platform-service:9082"
        - name: events
          ports:
            - containerPort: 9083
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/events"]
          env:
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
            - name: DAILY_REPORT_ENVIRONMENT
              value: prod
            - name: TEAMS_WEBHOOK_REPORT_BASE_URL
              value: https://prod-14.westus.logic.azure.com:443
            - name: TEAMS_WEBHOOK_WEEKLY_REPORT_BASE_URL
              value: https://prod-147.westus.logic.azure.com:443
        - name: metrics
          ports:
            - containerPort: 9082
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/metrics"]
          env:
            - name: VICTORIA_METRICS_API_URL
              value: "http://vmsingle-victoria-metrics-single:8429"
        - name: logsvc
          ports:
            - containerPort: 9084
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/logsvc"]
          env:
            - name: VICTORIA_LOGS_API_URL
              value: "http://cuemby-platform-victoria-logs-single-server:9428"
        - name: pauseworker
          ports:
            - containerPort: 9086
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/pauseworker"]
          env:
            - name: API_KEY
              value: {{ .Values.platform.environment.API_KEY | quote }}
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-platform-rabbitmq:5672"
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
            - name: WALRUS_USERNAME
              value: "admin"
            - name: WALRUS_BASE_URL
              value: "http://walru.walrus-system:80"
            - name: WALRUS_API_KEY
              value: ""
        - name: webhooks
          ports:
            - containerPort: 9087
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/webhooks"]
          env:
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-platform-rabbitmq:5672"
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
            - name: REDIS_ADDR
              value: http://cuemby-platform-redis-headless:6379
            - name: REDIS_USERNAME
              value: {{ .Values.redis.auth.username | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
            - name: REDIS_WEBHOOK_DB
              value: '55'
        - name: api
          ports:
            - containerPort: 9080
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/api"]
          env:
            - name: API_KEY
              value: {{ .Values.platform.environment.API_KEY | quote }}
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-platform-rabbitmq:5672"
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
            - name: MINIO_ACCESS_KEY_ID
              value: {{ .Values.platform.environment.MINIO_ACCESS_KEY_ID | quote }}
            - name: MINIO_SECRET_ACCESS_KEY
              value: {{ .Values.platform.environment.MINIO_SECRET_ACCESS_KEY | quote }}
            - name: MINIO_ENDPOINT
              value: {{ .Values.platform.environment.MINIO_ENDPOINT | quote }}
            - name: MINIO_REPORT_BUG_BUCKET
              value: reports-bug
            - name: LOGS_URL
              value: "http://platform-service:9084"
            - name: METRICS_URL
              value: "http://platform-service:9082"
            - name: WEBHOOKS_URL
              value: "http://platform-service:9087"
            - name: QUEUE_NAME_DELETION_WORKER
              value: "deletion_worker"
{{- end }}
