{{- if .Values.platform.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cuemby-system
  name: platform
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/component: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-service
      app.kubernetes.io/part-of: "platform-service"
      app.kubernetes.io/component: "platform-service"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform-service
        app.kubernetes.io/part-of: "platform-service"
        app.kubernetes.io/component: "platform-service"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/component"
                      operator: In
                      values:
                        - "platform"
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - "platform"
      restartPolicy: Always
      {{- with .Values.platform.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: deletion-worker
          ports:
            - containerPort: 9081
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/deletionworker"]
          env:
            {{- range $key, $value := .Values.platform.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-core-rabbitmq:5672"
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
              # value: "{{ .Values.platform.environment.POSTGRES_URI }}"
            - name: WALRUS_USERNAME
              value: "admin"
            - name: WALRUS_BASE_URL
              value: "https://walrus:80"
            - name: WALRUS_API_KEY
              value: ""
            - name: QUEUE_NAME_DELETION_WORKER
              value: "deletion_worker"
        - name: metrics
          ports:
            - containerPort: 9082
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/metrics"]
          env:
            - name: API_KEY
              value: ""
            - name: VICTORIA_METRICS_API_URL
              value: "http://vm:8428"
        - name: logsvc
          ports:
            - containerPort: 9084
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/logsvc"]
          env:
            - name: API_KEY
              value: ""
            - name: VICTORIA_LOGS_API_URL
              value: "http://vm:8428"
        - name: pauseworker
          ports:
            - containerPort: 9086
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/pauseworker"]
          env:
            {{- range $key, $value := .Values.platform.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-core-rabbitmq:5672"
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
        - name: webhooks
          ports:
            - containerPort: 9085
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/webhooks"]
          env:
            - name: API_KEY
              value: ""
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-core-rabbitmq:5672"
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
            - name: REDIS_ADDR
              value: "http://cuemby-core-redis:6379"
            - name: REDIS_USERNAME
              value: "default"
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
            - name: REDIS_WEBHOOK_DB
              value: "55"
        - name: api
          ports:
            - containerPort: 9080
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          command: ["/app/bin/api"]
          env:
            - name: API_KEY
              value: ""
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-core-rabbitmq:5672"
            - name: POSTGRES_URI
              value: "postgresql://{{ .Values.platform.environment.DB_USERNAME }}:{{ .Values.platform.environment.DB_PASSWORD }}@{{ .Values.platform.environment.DB_HOST }}:{{ .Values.platform.environment.DB_PORT }}/{{ .Values.platform.environment.DB_DATABASE }}"
            - name: MINIO_ACCESS_KEY_ID
              value: ""
            - name: MINIO_SECRET_ACCESS_KEY
              value: ""
            - name: MINIO_ENDPOINT
              value: ""
            - name: LOGS_URL
              value: "http://platform:9084"
            - name: METRICS_URL
              value: "http://platform:9082"
            - name: WEBHOOKS_URL
              value: "http://platform:9085"
{{- end }}
