{{- if .Values.platform.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cp-system
  name: platform
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/component: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-service
      app.kubernetes.io/part-of: "platform-service"
      app.kubernetes.io/component: "platform-service"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform-service
        app.kubernetes.io/part-of: "platform-service"
        app.kubernetes.io/component: "platform-service"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/component"
                      operator: In
                      values:
                        - "platform"
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - "platform"
      restartPolicy: Always
      {{- with .Values.platform.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: platform
          image: "{{ .Values.platform.image.repository }}:{{ .Values.platform.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.platform.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.platform.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: RABBIT_URI
              value: "amqp://{{ .Values.rabbitmq.auth.username }}:{{ .Values.rabbitmq.auth.password }}@cuemby-core-rabbitmq.default:5672"
          resources:
            limits:
              cpu: 2500m
              memory: 3Gi
            requests:
              cpu: 50m
              memory: 64Mi
{{- end }}
