{{- if .Values.platform.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: cuemby-system
  name: platform-service
  labels:
    app.kubernetes.io/name: platform-service
    app.kubernetes.io/part-of: "platform-service"
    app.kubernetes.io/component: "platform-service"
spec:
  selector:
    app.kubernetes.io/name: platform-service
    app.kubernetes.io/part-of: "platform-service"
    app.kubernetes.io/component: "platform-service"
  sessionAffinity: ClientIP
  type: {{ .Values.platform.service.type }}
  ports:
    - name: api-port-9080
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: deletionworker-port-9081
      protocol: TCP
      port: 9081
      targetPort: 9081
    - name: metrics-9082
      protocol: TCP
      port: 9082
      targetPort: 9082
    - name: events-port-9083
      protocol: TCP
      port: 9083
      targetPort: 9083
    - name: logsvc-port-9084
      protocol: TCP
      port: 9084
      targetPort: 9084
    - name: billingcron-port-9085
      protocol: TCP
      port: 9085
      targetPort: 9085
    - name: pauseworker-port-9086
      protocol: TCP
      port: 9086
      targetPort: 9086
    - name: webhooks-port-9087
      protocol: TCP
      port: 9087
      targetPort: 9087
{{- end }}
