---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: knative-selfsigned-issuer
spec:
  ca:
    secretName: knative-selfsigned-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-selfsigned-ca
  namespace: cert-manager
spec:
  secretName: knative-selfsigned-ca
  commonName: knative.dev
  usages:
    - server auth
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: cluster-selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: knative@cuemby.net
    privateKeySecretRef:
      name: letsencrypt-dns-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: cloudflare_api_token
              name: cloudflare-api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-wildcard-cloudflare
  namespace: knative-serving
spec:
  secretName: knative-wildcard-cloudflare
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: ClusterOriginIssuer
    name: origin-ca-issuer
  commonName: "*.app-shlab.cuemby.io"
  dnsNames:
    - "*.app-shlab.cuemby.io"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-wildcard-letsencrypt
  namespace: knative-serving
spec:
  secretName: knative-wildcard-letsencrypt
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  commonName: "*.app-shlab.cuemby.io"
  dnsNames:
    - "*.app-shlab.cuemby.io"
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    istio-injection: enabled
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    domain:
      app-shlab.cuemby.io: ""
    network:
      domain-template: "{{.Name}}.{{.Domain}}"
      external-domain-tls: Enabled
      http-protocol: Redirected
    certmanager:
      issuerRef: |
        group: cert-manager.k8s.cloudflare.com
        kind: ClusterOriginIssuer
        name: origin-ca-issuer
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "*"
            port:
              name: http
              number: 80
              protocol: HTTP
            tls:
              httpsRedirect: true
          - hosts:
              - "*"
            port:
              name: https
              number: 443
              protocol: HTTPS
            tls:
              mode: SIMPLE
              credentialName: knative-wildcard-cloudflare
# ---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-cluster-issuer
# spec:
#   acme:
#     email: {{ .Values.knative.email | quote }}
#     privateKeySecretRef:
#       name: letsencrypt-dns-key
#     server: https://acme-v02.api.letsencrypt.org/directory
#     solvers:
#       - dns01:
#           cloudflare:
#             apiTokenSecretRef:
#               key: cloudflare_api_token
#               name: cloudflare-api-token
