{{- if .Values.functions.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.functions.fullname" . }}-cp-config
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  WALRUS_BASE_URL: "http://walrus.walrus-system:80/v1"
  WALRUS_USERNAME: "admin"
  WALRUS_API_KEY: ""
  WALRUS_PASSWORD: ""
  KUBE_CONFIG: ""
  SWAGGER_API_KEY: ""
  SECURE_REPOS_INTERNAL_KEY: ""
{{- end }}
