{{- if .Values.configurator.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-walrus-db
  namespace: cuemby-system
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: psql
          image: postgres:16.1
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: cuemby-platform-core-db
                  key: password
            - name: PGHOST
              value: {{ .Values.configurator.environment.PGHOST | quote }}
            - name: PGUSER
              value: {{ .Values.configurator.environment.PGUSERNAME | quote }}
            - name: DBNAME
              value: walrus
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for DB to be ready..."
              for i in {1..120}; do
                pg_isready -h $PGHOST -p 5432 -U $PGUSER && break
                echo "Waiting... ($i)"
                sleep 5
              done

              echo "Creating database if not exists..."
              echo "SELECT 'CREATE DATABASE $DBNAME' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DBNAME')\\gexec" | psql -h $PGHOST -U $PGUSER -d postgres
{{- end }}
