{{- if .Values.configurator.enabled -}}
# Crear initContainer para la validacion de que ya esten listos para recibir peticiones de los servicio o pods (walrus, supabase-configMap)
apiVersion: batch/v1
kind: Job
metadata:
  name: cp-configurator
  namespace: cp-system
spec:
  backoffLimit: 4 # Number of retries before the job is considered failed
  activeDeadlineSeconds: 600 # Maximum time the job can run (10 minutes)
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.configurator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: cp-configurator-sa
      containers:
        - name: cp-configurator
          image: "{{ .Values.configurator.image.repository }}:{{ .Values.configurator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.configurator.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.configurator.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            # - name: PGPASSWORD
            #   value: ""
            # - name: PGUSERNAME
            #   value: ""
            # - name: DATABASE_NAME
            #   value: "http://walrus.walrus-system.svc.cluster.local:80"
            # - name: PGPORT
            #   value: ""
            # - name: PGHOST
            #   value: "default"
            # - name: GITHUB_CLIENT_ID
            #   value: ""
            # - name: GITHUB_CLIENT_SECRET
            #   value: ""
{{- end }}
