{{- if .Values.configurator.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: credentials-registry
  namespace: cp-system
  labels:
    app.kubernetes.io/name: cp-configurator
    app.kubernetes.io/component: cp-configurator
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "configurator.dockerconfigjson" . | b64enc | quote }}
{{- end }}
