{{- if .Values.db.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: cuemby-platform
  name: database
spec:
  selector:
    "app.kubernetes.io/part-of": "walrus"
    "app.kubernetes.io/component": "database"
  ports:
    - name: conn
      port: 5432
      targetPort: conn
{{- end }}
