{{- if include "core.knative.enabled" . | fromYaml }}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: knative-selfsigned-issuer
spec:
  ca:
    secretName: knative-selfsigned-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-selfsigned-ca
  namespace: cert-manager
spec:
  secretName: knative-selfsigned-ca
  commonName: knative.dev
  usages:
    - server auth
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: cluster-selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.knative.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.knative.letsencryptDnsKeySecretName | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: {{ .Values.knative.cloudflareApiTokenKey | quote }}
              name: {{ .Values.knative.cloudflareApiTokenSecretName | quote }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-wildcard-cloudflare
  namespace: knative-serving
spec:
  secretName: knative-wildcard-cloudflare
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: ClusterOriginIssuer
    name: origin-ca-issuer
  commonName: {{ .Values.knative.wildcardDomain | quote }}
  dnsNames:
    - {{ .Values.knative.wildcardDomain | quote }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-wildcard-letsencrypt
  namespace: knative-serving
spec:
  secretName: knative-wildcard-letsencrypt
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  commonName: {{ .Values.knative.wildcardDomain | quote }}
  dnsNames:
    - {{ .Values.knative.wildcardDomain | quote }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    istio-injection: enabled
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    domain:
      {{ .Values.knative.domain | quote }}: ""
    network:
      domain-template: "{{`{{.Name}}.{{.Domain}}`}}"
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: ingressgateway
        servers:
          - hosts:
              - "*"
            port:
              name: http
              number: 80
              protocol: HTTP
{{- end }} 