{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: walrus-system
  name: minio
  labels:
    "app.kubernetes.io/part-of": "walrus"
    "app.kubernetes.io/component": "minio"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
{{- end }}
