{{- if .Values.walrus.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-walrus-db
  labels:
    app.kubernetes.io/name: create-walrus-db
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: psql
          image: postgres:16.1
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: walrus-secrets
                  key: db_password
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for DB to be ready..."
              for i in {1..20}; do
                pg_isready -h cuemby-core-supabase-db -p 5432 -U supabase_admin && break
                echo "Waiting... ($i)"
                sleep 5
              done

              echo "Creating database if not exists..."
              echo "SELECT 'CREATE DATABASE walrus' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'walrus')\gexec" \
              | psql -h cuemby-core-supabase-db -U supabase_admin -d postgres
{{- end }}
