{{- if .Values.walrus.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cuemby-platform
  name: walrus
  labels:
    "app.kubernetes.io/part-of": "walrus"
    "app.kubernetes.io/component": "entrance"
spec:
  defaultBackend:
    service:
      name: walrus
      port:
        number: 80
{{- end }}
