{{- if .Values.walrus.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: walrus-system
  name: walrus
  labels:
    "app.kubernetes.io/part-of": "walrus"
    "app.kubernetes.io/component": "entrance"
spec:
  ingressClassName: {{ .Values.walrus.ingress.className }}
  rules:
    - host: {{ .Values.walrus.ingress.hosts.core }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: walrus
              port:
                number: 80
{{- end }}
