{{- if .Values.walrus.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: walrus-system
  labels:
    app.kubernetes.io/part-of: walrus
    app.kubernetes.io/component: walrus
    app.kubernetes.io/managed-by: helm
{{- end }}
