{{- if .Values.walrus.enabled -}}
{{- if .Values.walrus.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: walrus-system
  name: walrus
  labels:
    "app.kubernetes.io/part-of": "walrus"
    "app.kubernetes.io/component": "walrus"
spec:
  {{- if .Values.walrus.persistence.storageClass }}
  storageClassName: {{ .Values.walrus.persistence.storageClass }}
  {{- end }}
  accessModes:
  {{- range .Values.walrus.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.walrus.persistence.size | quote }}
{{- end }}
{{- end }}
