{{- if .Values.walrus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: cuemby-platform
  name: walrus-secrets
  labels:
    "app.kubernetes.io/part-of": "walrus"
    "app.kubernetes.io/component": "configuration"
stringData:
#   # Change to `true` if disabling TLS termination.
  local_environment_mode: "disabled"
  enable_tls: "false"
  db_driver: "postgres"
  db_user: "root"
  db_password: ""
  db_name: "walrus"
  minio_root_user: "minio"
  minio_root_password: ""
  minio_bucket: "walrus"
type: Opaque
{{- end }}
# Uncomment the following lines if consuming custom TLS.
#
