{{- if .Values.walrus.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: walrus-system
  name: walrus-secrets
  labels:
    "app.kubernetes.io/part-of": "walrus"
    "app.kubernetes.io/component": "configuration"
stringData:
# Change to `true` if disabling TLS termination.
  local_environment_mode: "disabled"
  enable_tls: "false"
  minio_root_user: {{ .Values.secret.minio.rootUser | quote }}
  minio_root_password: {{ .Values.secret.minio.rootPassword | quote }}
  minio_bucket: "walrus"

  db_driver: "postgres"
  db_user: {{ .Values.secret.db.user | quote }}
  db_password: {{ .Values.secret.db.password | quote }}
  db_name: "walrus"
  SERVER_SETTING_DEPLOYER_IMAGE: "cuembybot/terraform-deployer:1.9.2"
type: Opaque
{{- end }}
# Uncomment the following lines if consuming custom TLS.
