{{- if .Values.studio.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "supabase.studio.fullname" . }}-ingress
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.studio.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.studio.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.studio.ingress.host }}
      secretName: {{ include "supabase.studio.fullname" . }}-tls
  rules:
    - host: {{ .Values.studio.environment.SUPABASE_PUBLIC_URL | trimPrefix "http://" | trimPrefix "https://" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "supabase.studio.fullname" . }}
                port:
                  number: {{ .Values.studio.service.port }}
{{- end }}
