{{- if .Values.functions.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.functions.encryptionSecretName" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY_ENCRYPT_ECB: {{ include "supabase.functions.secretKeyEncryptECB" . }}
  SECRET_KEY_ENCRYPT_CBC: {{ include "supabase.functions.secretKeyEncryptCBC" . }}
  SECURE_REPOS_INTERNAL_KEY: {{ include "supabase.functions.secureReposInternalKey" . }}
{{- end }}
